// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) as total
FROM audit_logs
WHERE tenant_id = $1
`

func (q *Queries) CountAuditLogs(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, tenantID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getAuditLogsByAction = `-- name: GetAuditLogsByAction :many
SELECT 
    id,
    timestamp,
    actor_id,
    session_id,
    tenant_id,
    action,
    target_id,
    metadata,
    ip_address,
    user_agent,
    request_id
FROM audit_logs
WHERE tenant_id = $1 AND action = $2
ORDER BY timestamp DESC
LIMIT $3 OFFSET $4
`

type GetAuditLogsByActionParams struct {
	TenantID pgtype.UUID
	Action   string
	Limit    int32
	Offset   int32
}

func (q *Queries) GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByAction,
		arg.TenantID,
		arg.Action,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorID,
			&i.SessionID,
			&i.TenantID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUser = `-- name: GetAuditLogsByUser :many
SELECT 
    id,
    timestamp,
    actor_id,
    session_id,
    tenant_id,
    action,
    target_id,
    metadata,
    ip_address,
    user_agent,
    request_id
FROM audit_logs
WHERE tenant_id = $1 AND actor_id = $2
ORDER BY timestamp DESC
LIMIT $3 OFFSET $4
`

type GetAuditLogsByUserParams struct {
	TenantID pgtype.UUID
	ActorID  pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByUser,
		arg.TenantID,
		arg.ActorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorID,
			&i.SessionID,
			&i.TenantID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many

SELECT 
    id,
    timestamp,
    actor_id,
    session_id,
    tenant_id,
    action,
    target_id,
    metadata,
    ip_address,
    user_agent,
    request_id
FROM audit_logs
WHERE tenant_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	TenantID pgtype.UUID
	Limit    int32
	Offset   int32
}

// Audit Logs Queries
// Read-only queries for audit log API (writes handled by audit service)
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorID,
			&i.SessionID,
			&i.TenantID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
