// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    actor_id, 
    session_id, 
    tenant_id, 
    action, 
    target_id, 
    metadata, 
    ip_address, 
    user_agent, 
    request_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateAuditLogParams struct {
	ActorID   pgtype.UUID
	SessionID pgtype.UUID
	TenantID  pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
	Metadata  []byte
	IpAddress *netip.Addr
	UserAgent pgtype.Text
	RequestID pgtype.Text
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.SessionID,
		arg.TenantID,
		arg.Action,
		arg.TargetID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}

const listAuditLogsByTenant = `-- name: ListAuditLogsByTenant :many
SELECT id, timestamp, actor_id, session_id, tenant_id, action, target_id, metadata, ip_address, user_agent, request_id FROM audit_logs
WHERE tenant_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByTenantParams struct {
	TenantID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorID,
			&i.SessionID,
			&i.TenantID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, timestamp, actor_id, session_id, tenant_id, action, target_id, metadata, ip_address, user_agent, request_id FROM audit_logs
WHERE actor_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	ActorID pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.ActorID,
			&i.SessionID,
			&i.TenantID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
