// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: cleanup.sql

package db

import (
	"context"
)

const cleanExpiredInvitations = `-- name: CleanExpiredInvitations :execrows
DELETE FROM invitations 
WHERE expires_at < NOW()
`

// Uitnodigingen die nooit geaccepteerd zijn.
func (q *Queries) CleanExpiredInvitations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanExpiredInvitations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanExpiredRefreshTokens = `-- name: CleanExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens 
WHERE expires_at < NOW() 
   OR (is_revoked = TRUE AND revoked_at < NOW() - INTERVAL '30 days')
`

// Verwijder tokens die verlopen zijn OF die al langer dan 30 dagen revoked zijn.
func (q *Queries) CleanExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanExpiredVerificationTokens = `-- name: CleanExpiredVerificationTokens :execrows
DELETE FROM verification_tokens 
WHERE expires_at < NOW()
`

// Wachtwoord-resets en email-verificaties die niet gebruikt zijn.
func (q *Queries) CleanExpiredVerificationTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanExpiredVerificationTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanUsedMfaCodes = `-- name: CleanUsedMfaCodes :execrows
DELETE FROM mfa_backup_codes 
WHERE used = TRUE AND used_at < NOW() - INTERVAL '7 days'
`

// Backup codes die al gebruikt zijn (bewaar ze kort voor audit, daarna weg).
func (q *Queries) CleanUsedMfaCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanUsedMfaCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
