// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_changes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailChangeRequest = `-- name: CreateEmailChangeRequest :one
INSERT INTO email_change_requests (
    user_id, new_email, token_hash, expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, new_email, token_hash, used, used_at, expires_at, created_at
`

type CreateEmailChangeRequestParams struct {
	UserID    pgtype.UUID
	NewEmail  string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailChangeRequest(ctx context.Context, arg CreateEmailChangeRequestParams) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, createEmailChangeRequest,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.Used,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailChangeRequest = `-- name: GetEmailChangeRequest :one
SELECT id, user_id, new_email, token_hash, used, used_at, expires_at, created_at FROM email_change_requests
WHERE token_hash = $1 AND expires_at > NOW() AND used = FALSE
LIMIT 1
`

func (q *Queries) GetEmailChangeRequest(ctx context.Context, tokenHash string) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getEmailChangeRequest, tokenHash)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.Used,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailChangeRequestUsed = `-- name: MarkEmailChangeRequestUsed :exec
UPDATE email_change_requests
SET used = TRUE, used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailChangeRequestUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailChangeRequestUsed, id)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $2, is_email_verified = TRUE, updated_at = NOW()
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}
