// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations
SET accepted = TRUE
WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    email, token_hash, tenant_id, role, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, token_hash, tenant_id, role, expires_at, created_at, accepted
`

type CreateInvitationParams struct {
	Email     string
	TokenHash string
	TenantID  pgtype.UUID
	Role      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.TokenHash,
		arg.TenantID,
		arg.Role,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.TenantID,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Accepted,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE token_hash = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteInvitation, tokenHash)
	return err
}

const getInvitationByHash = `-- name: GetInvitationByHash :one
SELECT id, email, token_hash, tenant_id, role, expires_at, created_at, accepted FROM invitations
WHERE token_hash = $1 AND expires_at > NOW() AND accepted = FALSE
LIMIT 1
`

func (q *Queries) GetInvitationByHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.TenantID,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Accepted,
	)
	return i, err
}

const getPendingInvitationsByTenant = `-- name: GetPendingInvitationsByTenant :many
SELECT id, email, token_hash, tenant_id, role, expires_at, created_at, accepted FROM invitations
WHERE tenant_id = $1 AND accepted = FALSE
`

func (q *Queries) GetPendingInvitationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, getPendingInvitationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TokenHash,
			&i.TenantID,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Accepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
