// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIoTDevice = `-- name: CreateIoTDevice :one
INSERT INTO iot_devices (
    device_id, tenant_id, secret_hash, name
) VALUES (
    $1, $2, $3, $4
) RETURNING id, created_at
`

type CreateIoTDeviceParams struct {
	DeviceID   string
	TenantID   pgtype.UUID
	SecretHash string
	Name       string
}

type CreateIoTDeviceRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateIoTDevice(ctx context.Context, arg CreateIoTDeviceParams) (CreateIoTDeviceRow, error) {
	row := q.db.QueryRow(ctx, createIoTDevice,
		arg.DeviceID,
		arg.TenantID,
		arg.SecretHash,
		arg.Name,
	)
	var i CreateIoTDeviceRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getIoTDeviceByHardwareID = `-- name: GetIoTDeviceByHardwareID :one
SELECT id, tenant_id, secret_hash, is_active 
FROM iot_devices 
WHERE device_id = $1 LIMIT 1
`

type GetIoTDeviceByHardwareIDRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	SecretHash string
	IsActive   bool
}

func (q *Queries) GetIoTDeviceByHardwareID(ctx context.Context, deviceID string) (GetIoTDeviceByHardwareIDRow, error) {
	row := q.db.QueryRow(ctx, getIoTDeviceByHardwareID, deviceID)
	var i GetIoTDeviceByHardwareIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SecretHash,
		&i.IsActive,
	)
	return i, err
}

const listIoTDevices = `-- name: ListIoTDevices :many
SELECT id, device_id, tenant_id, secret_hash, name, is_active, last_seen_at, created_at, updated_at FROM iot_devices 
WHERE tenant_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListIoTDevices(ctx context.Context, tenantID pgtype.UUID) ([]IotDevice, error) {
	rows, err := q.db.Query(ctx, listIoTDevices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IotDevice
	for rows.Next() {
		var i IotDevice
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.TenantID,
			&i.SecretHash,
			&i.Name,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIoTDeviceHeartbeat = `-- name: UpdateIoTDeviceHeartbeat :exec
UPDATE iot_devices 
SET last_seen_at = NOW() 
WHERE id = $1
`

func (q *Queries) UpdateIoTDeviceHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateIoTDeviceHeartbeat, id)
	return err
}
