// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: mfa.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeBackupCode = `-- name: ConsumeBackupCode :exec
UPDATE mfa_backup_codes
SET used = TRUE, used_at = NOW()
WHERE id = $1
`

func (q *Queries) ConsumeBackupCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeBackupCode, id)
	return err
}

const countRemainingBackupCodes = `-- name: CountRemainingBackupCodes :one
SELECT count(*) FROM mfa_backup_codes
WHERE user_id = $1 AND used = FALSE
`

func (q *Queries) CountRemainingBackupCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRemainingBackupCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackupCode = `-- name: CreateBackupCode :exec
INSERT INTO mfa_backup_codes (user_id, code_hash) VALUES ($1, $2)
`

type CreateBackupCodeParams struct {
	UserID   pgtype.UUID
	CodeHash string
}

func (q *Queries) CreateBackupCode(ctx context.Context, arg CreateBackupCodeParams) error {
	_, err := q.db.Exec(ctx, createBackupCode, arg.UserID, arg.CodeHash)
	return err
}

type CreateBackupCodesParams struct {
	UserID   pgtype.UUID
	CodeHash string
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :exec
DELETE FROM mfa_backup_codes
WHERE user_id = $1
`

func (q *Queries) DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	return err
}

const getBackupCode = `-- name: GetBackupCode :one
SELECT id, user_id, code_hash, used, used_at, created_at FROM mfa_backup_codes
WHERE user_id = $1 AND code_hash = $2 AND used = FALSE
LIMIT 1
`

type GetBackupCodeParams struct {
	UserID   pgtype.UUID
	CodeHash string
}

func (q *Queries) GetBackupCode(ctx context.Context, arg GetBackupCodeParams) (MfaBackupCode, error) {
	row := q.db.QueryRow(ctx, getBackupCode, arg.UserID, arg.CodeHash)
	var i MfaBackupCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
