// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net"
	"net/netip"

	"github.com/Jeffreasy/LaventeCareAuthSystems/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	ActorID   pgtype.UUID
	SessionID pgtype.UUID
	TenantID  pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
	Metadata  []byte
	IpAddress *netip.Addr
	UserAgent pgtype.Text
	RequestID pgtype.Text
}

type EmailChangeRequest struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	NewEmail  string
	TokenHash string
	Used      bool
	UsedAt    pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Invitation struct {
	ID        pgtype.UUID
	Email     string
	TokenHash string
	TenantID  pgtype.UUID
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Accepted  bool
}

type Membership struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TenantID  pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type MfaBackupCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	Used      bool
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	ParentTokenID pgtype.UUID
	FamilyID      pgtype.UUID
	TenantID      pgtype.UUID
	IpAddress     net.IP
	UserAgent     pgtype.Text
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	IsRevoked     bool
	RevokedAt     pgtype.Timestamptz
}

type Tenant struct {
	ID             pgtype.UUID
	Name           string
	Slug           string
	PublicKey      pgtype.UUID
	SecretKeyHash  string
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AppUrl         string
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        pgtype.Text
	FullName            pgtype.Text
	IsEmailVerified     bool
	DefaultTenantID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	MfaSecret           pgtype.Text
	MfaEnabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
}

type VerificationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	Type      string
	TenantID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
