// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"net"
	"net/netip"

	"github.com/Jeffreasy/LaventeCareAuthSystems/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	ActorID   pgtype.UUID
	SessionID pgtype.UUID
	TenantID  pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
	Metadata  []byte
	IpAddress *netip.Addr
	UserAgent pgtype.Text
	RequestID pgtype.Text
}

type EmailChangeRequest struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	NewEmail  string
	TokenHash string
	Used      bool
	UsedAt    pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Audit trail for all email delivery attempts. Privacy-compliant: stores recipient hashes, not raw emails.
type EmailLog struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	// SHA256 hash of recipient email (GDPR pseudonymization)
	RecipientHash string
	TemplateType  string
	Status        string
	// External SMTP provider message ID for tracking
	ProviderMsgID pgtype.Text
	ProviderError pgtype.Text
	CreatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
	RetryCount    int32
	LastRetryAt   pgtype.Timestamptz
}

// Async email queue processed by background worker. Enables retry logic and prevents SMTP timeouts from blocking HTTP requests.
type EmailOutbox struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	// Serialized EmailPayload (JSONB). Contains recipient, template, and data.
	Payload    json.RawMessage
	Status     string
	RetryCount int32
	MaxRetries int32
	// When to retry sending (exponential backoff). NULL means immediate retry.
	NextRetryAt         pgtype.Timestamptz
	LastError           pgtype.Text
	CreatedAt           pgtype.Timestamptz
	ProcessingStartedAt pgtype.Timestamptz
	ProcessedAt         pgtype.Timestamptz
	EmailLogID          pgtype.UUID
}

type Invitation struct {
	ID        pgtype.UUID
	Email     string
	TokenHash string
	TenantID  pgtype.UUID
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Accepted  bool
}

type IotDevice struct {
	ID         pgtype.UUID
	DeviceID   string
	TenantID   pgtype.UUID
	SecretHash string
	Name       string
	IsActive   bool
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Membership struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TenantID  pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type MfaBackupCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	Used      bool
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	TokenHash     string
	ParentTokenID pgtype.UUID
	FamilyID      pgtype.UUID
	TenantID      pgtype.UUID
	IpAddress     net.IP
	UserAgent     pgtype.Text
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	IsRevoked     bool
	RevokedAt     pgtype.Timestamptz
}

type Tenant struct {
	ID             pgtype.UUID
	Name           string
	Slug           string
	PublicKey      pgtype.UUID
	SecretKeyHash  string
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AppUrl         string
	// SENSITIVE: Tenant-specific SMTP configuration with encrypted password. Only backend worker should read this. Use tenants_safe view for general queries.
	MailConfig []byte
	// Encryption key version for password rotation. Used by crypto.DecryptTenantSecretV().
	MailConfigKeyVersion pgtype.Int4
	Description          pgtype.Text
	Category             pgtype.Text
	IsFeatured           bool
	LogoUrl              pgtype.Text
	// Short catchy description for cards
	Tagline pgtype.Text
	// Array of technology or category tags
	Tags []string
	// Array of screenshot URLs
	GalleryUrls []string
	// JSON object for external links (twitter, linkedin, etc)
	SocialLinks []byte
}

// Security barrier view that excludes mail_config. Use this for frontend/API queries.
type TenantsSafe struct {
	ID             pgtype.UUID
	Name           string
	Slug           string
	PublicKey      pgtype.UUID
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       []byte
	Settings       []byte
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AppUrl         string
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        pgtype.Text
	FullName            pgtype.Text
	IsEmailVerified     bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	MfaSecret           pgtype.Text
	MfaEnabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	TenantID            pgtype.UUID
}

type VerificationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	Type      string
	TenantID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
