// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionsByUser = `-- name: GetSessionsByUser :many
SELECT id, user_id, token_hash, parent_token_id, family_id, tenant_id, ip_address, user_agent, expires_at, created_at, is_revoked, revoked_at FROM refresh_tokens
WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ParentTokenID,
			&i.FamilyID,
			&i.TenantID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.IsRevoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM refresh_tokens
WHERE id = $1 AND user_id = $2
`

type RevokeSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}
