// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/Jeffreasy/LaventeCareAuthSystems/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name, slug, secret_key_hash, allowed_origins, redirect_urls, branding, settings, app_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url
`

type CreateTenantParams struct {
	Name           string
	Slug           string
	SecretKeyHash  string
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	AppUrl         string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.SecretKeyHash,
		arg.AllowedOrigins,
		arg.RedirectUrls,
		arg.Branding,
		arg.Settings,
		arg.AppUrl,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
	)
	return i, err
}

const getTenantByPublicKey = `-- name: GetTenantByPublicKey :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url FROM tenants
WHERE public_key = $1 LIMIT 1
`

func (q *Queries) GetTenantByPublicKey(ctx context.Context, publicKey pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByPublicKey, publicKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
	)
	return i, err
}

const getTenantConfig = `-- name: GetTenantConfig :one
SELECT allowed_origins, app_url FROM tenants
WHERE id = $1
`

type GetTenantConfigRow struct {
	AllowedOrigins []string
	AppUrl         string
}

func (q *Queries) GetTenantConfig(ctx context.Context, id pgtype.UUID) (GetTenantConfigRow, error) {
	row := q.db.QueryRow(ctx, getTenantConfig, id)
	var i GetTenantConfigRow
	err := row.Scan(&i.AllowedOrigins, &i.AppUrl)
	return i, err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenants
SET 
    allowed_origins = $2,
    redirect_urls = $3,
    branding = $4,
    settings = $5,
    updated_at = NOW(),
    app_url = $6
WHERE id = $1
RETURNING id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url
`

type UpdateTenantConfigParams struct {
	ID             pgtype.UUID
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	AppUrl         string
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantConfig,
		arg.ID,
		arg.AllowedOrigins,
		arg.RedirectUrls,
		arg.Branding,
		arg.Settings,
		arg.AppUrl,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
	)
	return i, err
}
