// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/Jeffreasy/LaventeCareAuthSystems/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name, slug, secret_key_hash, allowed_origins, redirect_urls, branding, settings, app_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url, mail_config, mail_config_key_version, description, category, is_featured, logo_url, tagline, tags, gallery_urls, social_links
`

type CreateTenantParams struct {
	Name           string
	Slug           string
	SecretKeyHash  string
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	AppUrl         string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.SecretKeyHash,
		arg.AllowedOrigins,
		arg.RedirectUrls,
		arg.Branding,
		arg.Settings,
		arg.AppUrl,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
		&i.MailConfig,
		&i.MailConfigKeyVersion,
		&i.Description,
		&i.Category,
		&i.IsFeatured,
		&i.LogoUrl,
		&i.Tagline,
		&i.Tags,
		&i.GalleryUrls,
		&i.SocialLinks,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url, mail_config, mail_config_key_version, description, category, is_featured, logo_url, tagline, tags, gallery_urls, social_links FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
		&i.MailConfig,
		&i.MailConfigKeyVersion,
		&i.Description,
		&i.Category,
		&i.IsFeatured,
		&i.LogoUrl,
		&i.Tagline,
		&i.Tags,
		&i.GalleryUrls,
		&i.SocialLinks,
	)
	return i, err
}

const getTenantByPublicKey = `-- name: GetTenantByPublicKey :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url, mail_config, mail_config_key_version, description, category, is_featured, logo_url, tagline, tags, gallery_urls, social_links FROM tenants
WHERE public_key = $1 LIMIT 1
`

func (q *Queries) GetTenantByPublicKey(ctx context.Context, publicKey pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByPublicKey, publicKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
		&i.MailConfig,
		&i.MailConfigKeyVersion,
		&i.Description,
		&i.Category,
		&i.IsFeatured,
		&i.LogoUrl,
		&i.Tagline,
		&i.Tags,
		&i.GalleryUrls,
		&i.SocialLinks,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url, mail_config, mail_config_key_version, description, category, is_featured, logo_url, tagline, tags, gallery_urls, social_links FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
		&i.MailConfig,
		&i.MailConfigKeyVersion,
		&i.Description,
		&i.Category,
		&i.IsFeatured,
		&i.LogoUrl,
		&i.Tagline,
		&i.Tags,
		&i.GalleryUrls,
		&i.SocialLinks,
	)
	return i, err
}

const getTenantConfig = `-- name: GetTenantConfig :one
SELECT allowed_origins, app_url FROM tenants
WHERE id = $1
`

type GetTenantConfigRow struct {
	AllowedOrigins []string
	AppUrl         string
}

func (q *Queries) GetTenantConfig(ctx context.Context, id pgtype.UUID) (GetTenantConfigRow, error) {
	row := q.db.QueryRow(ctx, getTenantConfig, id)
	var i GetTenantConfigRow
	err := row.Scan(&i.AllowedOrigins, &i.AppUrl)
	return i, err
}

const listShowcaseTenants = `-- name: ListShowcaseTenants :many
SELECT name, slug, app_url, logo_url, description, category, tagline, tags, gallery_urls, social_links
FROM tenants 
WHERE is_featured = true 
ORDER BY name ASC
`

type ListShowcaseTenantsRow struct {
	Name        string
	Slug        string
	AppUrl      string
	LogoUrl     pgtype.Text
	Description pgtype.Text
	Category    pgtype.Text
	Tagline     pgtype.Text
	Tags        []string
	GalleryUrls []string
	SocialLinks []byte
}

func (q *Queries) ListShowcaseTenants(ctx context.Context) ([]ListShowcaseTenantsRow, error) {
	rows, err := q.db.Query(ctx, listShowcaseTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShowcaseTenantsRow
	for rows.Next() {
		var i ListShowcaseTenantsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.AppUrl,
			&i.LogoUrl,
			&i.Description,
			&i.Category,
			&i.Tagline,
			&i.Tags,
			&i.GalleryUrls,
			&i.SocialLinks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenants
SET 
    allowed_origins = $2,
    redirect_urls = $3,
    branding = $4,
    settings = $5,
    updated_at = NOW(),
    app_url = $6
WHERE id = $1
RETURNING id, name, slug, public_key, secret_key_hash, allowed_origins, redirect_urls, branding, settings, is_active, created_at, updated_at, app_url, mail_config, mail_config_key_version, description, category, is_featured, logo_url, tagline, tags, gallery_urls, social_links
`

type UpdateTenantConfigParams struct {
	ID             pgtype.UUID
	AllowedOrigins []string
	RedirectUrls   []string
	Branding       domain.TenantBranding
	Settings       domain.TenantSettings
	AppUrl         string
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantConfig,
		arg.ID,
		arg.AllowedOrigins,
		arg.RedirectUrls,
		arg.Branding,
		arg.Settings,
		arg.AppUrl,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PublicKey,
		&i.SecretKeyHash,
		&i.AllowedOrigins,
		&i.RedirectUrls,
		&i.Branding,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppUrl,
		&i.MailConfig,
		&i.MailConfigKeyVersion,
		&i.Description,
		&i.Category,
		&i.IsFeatured,
		&i.LogoUrl,
		&i.Tagline,
		&i.Tags,
		&i.GalleryUrls,
		&i.SocialLinks,
	)
	return i, err
}
