// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: tokens.sql

package db

import (
	"context"
	"net"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token_hash, parent_token_id, family_id, tenant_id, ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, token_hash, parent_token_id, family_id, tenant_id, ip_address, user_agent, expires_at, created_at, is_revoked, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID        pgtype.UUID
	TokenHash     string
	ParentTokenID pgtype.UUID
	FamilyID      pgtype.UUID
	TenantID      pgtype.UUID
	IpAddress     net.IP
	UserAgent     pgtype.Text
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ParentTokenID,
		arg.FamilyID,
		arg.TenantID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.FamilyID,
		&i.TenantID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.RevokedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (
    user_id, token_hash, type, tenant_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, token_hash, type, tenant_id, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	Type      string
	TenantID  pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.TenantID,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.TenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens
WHERE id = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, id)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, parent_token_id, family_id, tenant_id, ip_address, user_agent, expires_at, created_at, is_revoked, revoked_at FROM refresh_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.FamilyID,
		&i.TenantID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.RevokedAt,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT id, user_id, token_hash, type, tenant_id, expires_at, created_at FROM verification_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.TenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET is_revoked = TRUE, revoked_at = NOW(), updated_at = NOW()
WHERE family_id = $1 AND tenant_id = $2
`

type RevokeRefreshTokenFamilyParams struct {
	FamilyID pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.FamilyID, arg.TenantID)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE refresh_tokens
SET is_revoked = TRUE, revoked_at = NOW(), updated_at = NOW()
WHERE family_id = (
    SELECT rt.family_id FROM refresh_tokens rt WHERE rt.token_hash = $1
)
`

func (q *Queries) RevokeTokenFamily(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, tokenHash)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
WITH old_token AS (
    UPDATE refresh_tokens 
    SET is_revoked = TRUE, revoked_at = NOW(), updated_at = NOW()
    WHERE refresh_tokens.token_hash = $5
    RETURNING id, family_id, user_id, tenant_id
)
INSERT INTO refresh_tokens (
    token_hash, user_id, family_id, parent_token_id, expires_at, ip_address, user_agent, tenant_id
) 
SELECT 
    $1, 
    user_id, 
    family_id, 
    id, 
    $2,
    $3,
    $4,
    tenant_id
FROM old_token
RETURNING id, user_id, token_hash, parent_token_id, family_id, tenant_id, ip_address, user_agent, expires_at, created_at, is_revoked, revoked_at
`

type RotateRefreshTokenParams struct {
	NewTokenHash string
	ExpiresAt    pgtype.Timestamptz
	IpAddress    net.IP
	UserAgent    pgtype.Text
	OldTokenHash string
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken,
		arg.NewTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.OldTokenHash,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.FamilyID,
		&i.TenantID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.RevokedAt,
	)
	return i, err
}
