// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, full_name, tenant_id, mfa_secret, mfa_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id
`

type CreateUserParams struct {
	Email        string
	PasswordHash pgtype.Text
	FullName     pgtype.Text
	TenantID     pgtype.UUID
	MfaSecret    pgtype.Text
	MfaEnabled   bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.TenantID,
		arg.MfaSecret,
		arg.MfaEnabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const createUserFromInvitation = `-- name: CreateUserFromInvitation :one
WITH new_user AS (
    INSERT INTO users (email, password_hash, is_email_verified, tenant_id)
    VALUES ($1, $2, TRUE, $3) -- Tenant Scoped!
    RETURNING id, email, created_at
),
new_membership AS (
    INSERT INTO memberships (user_id, tenant_id, role)
    SELECT id, $3, $4
    FROM new_user
    RETURNING user_id
),
deleted_invite AS (
    DELETE FROM invitations 
    WHERE token_hash = $5
)
SELECT id, email, created_at FROM new_user
`

type CreateUserFromInvitationParams struct {
	Email        string
	PasswordHash pgtype.Text
	TenantID     pgtype.UUID
	Role         string
	TokenHash    string
}

type CreateUserFromInvitationRow struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserFromInvitation(ctx context.Context, arg CreateUserFromInvitationParams) (CreateUserFromInvitationRow, error) {
	row := q.db.QueryRow(ctx, createUserFromInvitation,
		arg.Email,
		arg.PasswordHash,
		arg.TenantID,
		arg.Role,
		arg.TokenHash,
	)
	var i CreateUserFromInvitationRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const createUserWithMembership = `-- name: CreateUserWithMembership :one
WITH new_user AS (
    INSERT INTO users (email, password_hash, full_name, tenant_id, mfa_secret, mfa_enabled)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
    RETURNING id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id
),
new_membership AS (
    INSERT INTO memberships (user_id, tenant_id, role)
    SELECT new_user.id, $4, $7
    FROM new_user
    RETURNING user_id
)
SELECT id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id FROM new_user
`

type CreateUserWithMembershipParams struct {
	Email        string
	PasswordHash pgtype.Text
	FullName     pgtype.Text
	TenantID     pgtype.UUID
	MfaSecret    pgtype.Text
	MfaEnabled   bool
	Role         string
}

type CreateUserWithMembershipRow struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        pgtype.Text
	FullName            pgtype.Text
	IsEmailVerified     bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	MfaSecret           pgtype.Text
	MfaEnabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	TenantID            pgtype.UUID
}

// Atomically creates a user and their default tenant membership
// Note: TenantID is now MANDATORY for the user itself.
func (q *Queries) CreateUserWithMembership(ctx context.Context, arg CreateUserWithMembershipParams) (CreateUserWithMembershipRow, error) {
	row := q.db.QueryRow(ctx, createUserWithMembership,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.TenantID,
		arg.MfaSecret,
		arg.MfaEnabled,
		arg.Role,
	)
	var i CreateUserWithMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id FROM users
WHERE email = $1 AND tenant_id = $2 LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string
	TenantID pgtype.UUID
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id FROM users
WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetUserByIDParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const getUserContext = `-- name: GetUserContext :one
SELECT 
    u.id, 
    u.email, 
    u.full_name,
    m.role,
    t.id as tenant_id,
    t.slug as tenant_slug
FROM users u
JOIN memberships m ON u.id = m.user_id
JOIN tenants t ON m.tenant_id = t.id
WHERE u.id = $1 AND t.id = $2
`

type GetUserContextParams struct {
	ID   pgtype.UUID
	ID_2 pgtype.UUID
}

type GetUserContextRow struct {
	ID         pgtype.UUID
	Email      string
	FullName   pgtype.Text
	Role       string
	TenantID   pgtype.UUID
	TenantSlug string
}

func (q *Queries) GetUserContext(ctx context.Context, arg GetUserContextParams) (GetUserContextRow, error) {
	row := q.db.QueryRow(ctx, getUserContext, arg.ID, arg.ID_2)
	var i GetUserContextRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.TenantID,
		&i.TenantSlug,
	)
	return i, err
}

const incrementLoginAttempts = `-- name: IncrementLoginAttempts :exec
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLoginAttempts, id)
	return err
}

const lockUserAccount = `-- name: LockUserAccount :exec
UPDATE users
SET locked_until = $2, failed_login_attempts = 0, updated_at = NOW()
WHERE id = $1
`

type LockUserAccountParams struct {
	ID          pgtype.UUID
	LockedUntil pgtype.Timestamptz
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) error {
	_, err := q.db.Exec(ctx, lockUserAccount, arg.ID, arg.LockedUntil)
	return err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0, locked_until = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, id)
	return err
}

const updateUserMFA = `-- name: UpdateUserMFA :one
UPDATE users
SET mfa_secret = $2, mfa_enabled = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id
`

type UpdateUserMFAParams struct {
	ID         pgtype.UUID
	MfaSecret  pgtype.Text
	MfaEnabled bool
}

func (q *Queries) UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserMFA, arg.ID, arg.MfaSecret, arg.MfaEnabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET 
    full_name = COALESCE($1, full_name),
    updated_at = NOW()
WHERE id = $2
`

type UpdateUserProfileParams struct {
	FullName pgtype.Text
	ID       pgtype.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.FullName, arg.ID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET is_email_verified = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, is_email_verified, created_at, updated_at, mfa_secret, mfa_enabled, failed_login_attempts, locked_until, tenant_id
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TenantID,
	)
	return i, err
}
