package domain

import (
	"encoding/json"
)

// ---------------------------------------------------------
// JSONB Helpers (Nodig voor Branding & Settings)
// ---------------------------------------------------------

type TenantBranding struct {
	LogoURL      *string `json:"logo_url"` // Pointer, want kan null zijn
	PrimaryColor string  `json:"primary_color"`
}

// Scan zorgt ervoor dat de database JSON bytes automatisch omzet naar de struct
func (tb *TenantBranding) Scan(src interface{}) error {
	if src == nil {
		return nil
	}
	// Type assertion: src is []byte in pgx
	return json.Unmarshal(src.([]byte), tb)
}

type TenantSettings struct {
	AllowRegistration bool `json:"allow_registration"`
}

func (ts *TenantSettings) Scan(src interface{}) error {
	if src == nil {
		return nil
	}
	return json.Unmarshal(src.([]byte), ts)
}

// ---------------------------------------------------------
// Database Models
// ---------------------------------------------------------

// Tenant struct is removed because it is generated by sqlc in internal/storage/db/models.go
// We keep this file for the JSONB helper structs below.
